platform :ios, '8.0'
#use_frameworks!

target 'HorizontalScrollTableViewCell_Example' do
    pod 'HorizontalScrollTableViewCell'
    
    target 'HorizontalScrollTableViewCell_Tests' do
        inherit! :search_paths
        
        
    end
end


